# Generated by Django 4.2.3 on 2023-07-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='WebView title')),
                ('url', models.URLField(max_length=100)),
                ('list_of_auto_fields', models.JSONField(max_length=100)),
            ],
        ),
    ]
