# Generated by Django 4.2.3 on 2023-07-20 10:01

from django.db import migrations, models
import wvs_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('wvs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wv',
            name='list_of_auto_fields',
            field=models.JSONField(default=wvs_api.models.get_default_auto_fields, max_length=100),
        ),
    ]
