# Generated by Django 4.2.3 on 2023-07-20 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schedule_api.models
import schedule_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_api', '0010_sublist_wvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_file', models.FileField(max_length=50, upload_to=schedule_api.models.Schedule.get_schedule_path, validators=[django.core.validators.FileExtensionValidator(['json']), schedule_api.validators.FileValidator(limit_value=102400)], verbose_name='Schedule file')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_course_group', to='core_api.coursegroup')),
            ],
        ),
    ]
