# Generated by Django 4.2.3 on 2023-07-19 14:33

import django.core.validators
from django.db import migrations, models
import maps_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
        migrations.AlterField(
            model_name='map',
            name='map_file',
            field=models.FileField(default=1, upload_to=maps_api.models.Map.get_map_path, validators=[django.core.validators.FileExtensionValidator(['png'])]),
            preserve_default=False,
        ),
    ]
