# Generated by Django 4.2.3 on 2023-07-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_alter_coursegroup_options_and_more'),
        ('manual_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopost',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_info_posts', to='manual_api.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='direction',
            field=models.ManyToManyField(related_name='direction_subjects', to='core_api.direction'),
        ),
    ]
