# Generated by Django 4.2.3 on 2023-07-19 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0002_alter_faculty_options_alter_faculty_title_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Course number')),
                ('group_number', models.IntegerField(verbose_name='Group number')),
                ('subgroup_number', models.IntegerField(verbose_name='Subgroup number')),
                ('education_level', models.CharField(choices=[('b', 'bachelor'), ('m', 'magistracy'), ('p', 'postgraduate'), ('s', 'specialty')], max_length=1, verbose_name='Education level')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='core_api.direction')),
            ],
            options={
                'verbose_name': 'CourseGroup',
                'verbose_name_plural': 'CourseGroups',
            },
        ),
        migrations.CreateModel(
            name='SubList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Direction title')),
                ('additional_course_groups', models.ManyToManyField(related_name='sub_list_add_course_group', to='core_api.coursegroup')),
                ('main_course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_list_main_course_group', to='core_api.coursegroup')),
                ('main_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_sub_list', to='core_api.direction')),
                ('main_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_sub_list', to='core_api.faculty')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
