# Generated by Django 4.2.3 on 2023-07-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_coursegroup_sublist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublist',
            name='main_faculty',
        ),
    ]
