# Generated by Django 4.2.3 on 2023-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_remove_sublist_main_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='subgroup_number',
            field=models.IntegerField(null=True, verbose_name='Subgroup number'),
        ),
    ]
