# Generated by Django 4.2.3 on 2023-07-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_alter_coursegroup_subgroup_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegroup',
            old_name='faculty',
            new_name='direction',
        ),
    ]
