# Generated by Django 4.2.3 on 2023-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_rename_faculty_coursegroup_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='subgroup_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subgroup number'),
        ),
    ]
