# Generated by Django 4.2.3 on 2023-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_api', '0002_alter_map_options_alter_map_map_file'),
        ('core_api', '0008_alter_sublist_additional_course_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublist',
            name='buildings',
            field=models.ManyToManyField(related_name='sub_list_buildings', to='maps_api.building'),
        ),
    ]
