# Generated by Django 4.2.3 on 2023-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wvs_api', '0002_alter_wv_list_of_auto_fields'),
        ('core_api', '0009_sublist_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublist',
            name='wvs',
            field=models.ManyToManyField(related_name='sub_list_wvs', to='wvs_api.wv'),
        ),
    ]
