# Generated by Django 4.2.3 on 2023-07-20 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps_api', '0002_alter_map_options_alter_map_map_file'),
        ('wvs_api', '0002_alter_wv_list_of_auto_fields'),
        ('core_api', '0010_sublist_wvs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'verbose_name': 'Course Group', 'verbose_name_plural': 'Course Groups'},
        ),
        migrations.AlterField(
            model_name='sublist',
            name='additional_course_groups',
            field=models.ManyToManyField(limit_choices_to=models.Q(('id', models.F('add_course_group_sub_lists')), _negated=True), related_name='add_course_group_sub_lists', to='core_api.coursegroup'),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='buildings',
            field=models.ManyToManyField(related_name='building_sub_lists', to='maps_api.building'),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='main_course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_course_group_sub_lists', to='core_api.coursegroup'),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='main_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_sub_lists', to='core_api.direction'),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='wvs',
            field=models.ManyToManyField(related_name='wv_sub_lists', to='wvs_api.wv'),
        ),
    ]
