# Generated by Django 4.2.3 on 2023-07-20 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_api', '0010_sublist_wvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event title')),
                ('description', models.TextField(max_length=800, verbose_name='Event description')),
                ('event_start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event start date')),
                ('event_end_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event end date')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='Is event full day')),
                ('e_type', models.CharField(choices=[('i', 'Info'), ('e', 'Exam'), ('a', 'Attestation'), ('h', 'Holiday')], max_length=1, verbose_name='Event type')),
                ('course_groups', models.ManyToManyField(blank=True, default=None, related_name='course_group_events', to='core_api.coursegroup')),
            ],
        ),
    ]
