# Generated by Django 4.2.3 on 2023-07-20 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_api', '0011_alter_coursegroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Pub Group title')),
                ('url', models.URLField(max_length=100, unique=True, verbose_name='Group url')),
                ('last_parse', models.DateTimeField(null=True, verbose_name='Group last parse date')),
                ('faculties', models.ManyToManyField(related_name='faculty_pub_groups', to='core_api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pub title')),
                ('body_text', models.TextField(max_length=10000, verbose_name='Pub body text')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pub time')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_group_publications', to='publications_api.pubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PubTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Tag title')),
            ],
        ),
        migrations.CreateModel(
            name='PubPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nb', models.IntegerField(help_text='Starts from 0', verbose_name='Pic order number')),
                ('url', models.URLField(max_length=100, verbose_name='Pub picture url')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_pictures', to='publications_api.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(related_name='pub_tag_publications', to='publications_api.pubtag'),
        ),
        migrations.AddField(
            model_name='pubgroup',
            name='tags',
            field=models.ManyToManyField(related_name='pub_tag_pub_groups', to='publications_api.pubtag'),
        ),
    ]
